<?php
/**
 * @var $block \Resursbank\Omnicheckout\Block\Carriers
 */
?>

<?php $rates = $block->getRates() ?>
<?php $index = 1; ?>

<?php if (count($rates)): ?>
    <div class="checkout-shipping-method">
        <div class="step-title" data-bind="<?php echo __('Shipping Methods') ?>" data-role="title"><?php echo __('Shipping Methods') ?></div>
        <div id="checkout-step-shipping_method" class="step-content" data-role="content" role="tabpanel" aria-hidden="false">
            <form class="form methods-shipping" id="co-shipping-method-form" data-bind="submit: setShippingInformation" novalidate="novalidate">
                <div id="checkout-shipping-method-load">
                    <table class="table-checkout-shipping-method">
                        <thead>
                            <tr class="row">
                                <th class="col col-method" data-bind="<?php echo __('Select Method') ?>"><?php echo __('Select Method') ?></th>
                                <th class="col col-price" data-bind="<?php echo __('Price') ?>"><?php echo __('Price') ?></th>
                                <th class="col col-method" data-bind="<?php echo __('Method Title') ?>"><?php echo __('Method Title') ?></th>
                                <th class="col col-carrier" data-bind="<?php echo __('Carrier Title') ?>"><?php echo __('Carrier Title') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($rates as $rate): ?>
                                <tr class="row" data-bind="click: $parent.selectShippingMethod">
                                    <td class="col col-method">
                                        <input type="radio" data-bind="
                                                        value: method.carrier_code + '_' + method.method_code,
                                                        checked: $parent.isSelected,
                                                        attr: {
                                                            'id': 's_method_' + method.carrier_code + '_' + method.method_code,
                                                            'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code
                                                        },
                                                        click: $parent.selectShippingMethod" class="radio" value="<?php echo "{$rate->getCarrier()}_{$rate->getCode()}" ?>" id="s_method_<?php echo "{$rate->getCarrier()}_{$rate->getCode()}" ?>" aria-labelledby="label_method_<?php echo "{$rate->getCarrier()}_{$rate->getCode()}" ?> label_carrier_<?php echo "{$rate->getCarrier()}_{$rate->getCode()}" ?>" name="shipping_method">
                                    </td>
                                    <td class="col col-price">
                                        <span class="price"><span class="price" data-bind="text: getFormattedPrice(method.price_excl_tax)"><?php echo $block->formatPrice($rate->getPrice()) ?></span></span>
                                    </td>
                                    <td class="col col-method" data-bind="text: method.method_title, attr: {'id': 'label_method_' + method.method_code + '_' + method.carrier_code}" id="label_method_<?php echo "{$rate->getCarrier()}_{$rate->getCode()}" ?>"><?php echo $rate->getCarrierTitle() ?></td>
                                    <td class="col col-carrier" data-bind="text: method.carrier_title, attr: {'id': 'label_carrier_' + method.method_code + '_' + method.carrier_code}" id="label_carrier_<?php echo "{$rate->getCarrier()}_{$rate->getCode()}" ?>"><?php echo $rate->getMethodTitle() ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>
