<?php
/**
 * Template for payment session iframe in checkout.
 *
 * @var $this Resursbank\OmniCheckout\Block\Iframe
 */
?>
<?php if ($this->getApiModel()->paymentSessionInitialized()): ?>
    <div id="omnicheckout-iframe-container">
        <?php echo preg_replace('#<script(.*?)>(.*?)</script>#is', '', $this->getApiModel()->getSessionIframeHtml()) ?>
    </div>
<?php else: ?>
    <div class="resursbank-messages">
        <p class="payment-gateway-connection-error"><?php echo __('The connection to the payment gateway failed and thus you cannot proceed to our checkout. Please try again in a few minutes.') ?></p>
    </div>
<?php endif; ?>
