<?php
/**
 * Copyright 2016 Resurs Bank AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<?php
/**
 * Template for payment session iframe in checkout.
 *
 * @var $block \Resursbank\OmniCheckout\Block\Iframe
 */
?>

<div class="omni-clear"><!-- CLEAR FLOATS --></div>

<?php if ($block->getApiModel()->paymentSessionInitialized()): ?>
        <div id="omnicheckout-iframe-container">
<!--            --><?php //echo preg_replace('#<iframe(.*?)>(.*?)</iframe>#is', '', $block->getApiModel()->getSessionIframeHtml()); ?>
        </div>
<?php else: ?>
    <div class="resursbank-messages">
        <p class="payment-gateway-connection-error"><?php echo __('The connection to the payment gateway failed and thus you cannot proceed to our checkout. Please try again in a few minutes.') ?></p>
    </div>
<?php endif; ?>
