<?php
/**
 * @var $block \Resursbank\Omnicheckout\Block\Js
 */
?>

<script>
    require([
        'Resursbank_OmniCheckout/js/omnicheckout'
    ], function(omnicheckout) {
        omnicheckout.init({
            baseUrl: '<?php echo $block->getBaseUrl(); ?>',
            formKey: '<?php echo $block->escapeHtml($block->getFormKey()); ?>',
            iframeUrl: '<?php echo $block->getApiModel()->getIframeUrl(); ?>'
        });
    });
</script>
