<?php
/**
 * Copyright 2016 Resurs Bank AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<?php
/**
 * @var $block \Resursbank\Omnicheckout\Block\Js
 */
?>

<script>
    require([
        'domReady',
        'Resursbank_OmniCheckout/js/omnicheckout'
    ], function(
        domReady,
        omnicheckout
    ) {
        domReady(function () {
            omnicheckout.init({
                baseUrl: '<?php echo $block->getBaseUrl(); ?>',
                formKey: '<?php echo $block->escapeHtml($block->getFormKey()); ?>',
                iframeUrl: '<?php echo $block->getApiModel()->getIframeUrl(); ?>',
                iframe: '<?php echo preg_replace('#<script(.*?)>(.*?)</script>#is', '', $block->getApiModel()->getSessionIframeHtml()); ?>'
            });
        });
    });
</script>
