<?php
/**
 * Copyright 2016 Resurs Bank AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<?php
/**
 * @var $block \Resursbank\OmniCheckout\Block\Adminhtml\System\Config\Callback\Listing
 */
?>

<?php $callbacks = $block->getCallbacks(); ?>

<?php if (count($callbacks)): ?>

    <div>
        <?php foreach ($callbacks as $callback): ?>
            <p><b>[<?php echo $callback->eventType ?> ]</b></p>
            <p style="margin-bottom:10px; padding-bottom:10px; border-bottom:1px dashed #c0c0c0;"><?php echo $callback->uriTemplate ?></p>
        <?php endforeach; ?>
    </div>

<?php endif; ?>